Update olefile version contraint
openpreserve/fido pull request #195
Opened 2021-02-24 07:39 UTC by sevein

This commit ensures that fido uses olefile~=0.46 which makes possible to use OleFileIO as a context manager.

It potentially fixes https://github.com/openpreserve/fido/issues/179, assuming that the user had and older release of olefile installed. That would explain the error reported, where `__enter__` seems to be missing.

```
File "/usr/local/lib/python3.6/dist-packages/opf_fido-1.4.0-py3.6.egg/fido/package.py", line 40, in detect_formats
  with olefile.OleFileIO(self.ole) as ole:
AttributeError: __enter__
```

2021-02-27 21:43 UTC, carlwilson submitted a review, later dismissed

2021-02-27 21:46 UTC, carlwilson requested changes
Hi @sevein while the work's obviously fine it would be better if the PR was against the [release candidate branch](https://github.com/openpreserve/fido/tree/rc/1.6) rather than master if that's OK thanks.

2021-03-01 07:54 UTC, sevein commented
> Hi @sevein while the work's obviously fine it would be better if the PR was against the release candidate branch rather than master if that's OK thanks.
Done!

2021-03-01 12:49 UTC, carlwilson approved these changes

2021-03-01 12:49 UTC, carlwilson commented
@sevein, feel free to merge :)

2021-03-01 14:47 UTC, merged